### ISSUE TITLE
Escape non-alphanumerics when printing env vars

### ISSUE THREAD

**Issue by andreypopp** [esy-ocaml-old/esy-old#3]
We need to replace non-alphanumerics when printing env vars. The source of those chars are package names whcih are allowed to contain `-` and `.` symbols (maybe more?).

- [ ] We escape `-` by converting it to `_` but it clashes with `_` in the original package name. *Suggestion:* replace `-` with `__dash__`.
- [ ] We need to escape `.`. *Suggestion:*  replace`.` with `__dot__`.

That way `socket.io` will become `socket__dot__io` and `core-js` — `core__dash__js`.

Thoughts?

**Comment by jordwalke** [comment]
yeah, this sounds good. Only problem remaining is if the package name has `__` in it, then it conflicts with builtins like `react__install`, but this should be so rare it doesn't matter.

**Comment by andreypopp** [comment]
> `package-name` becoming `package__name`

I propose converting `-` to `__dash__` so it will become `package__dash__name` (not the double underscore).

**Comment by bsansouci** [comment]
Yeah I think esy doesn't like `.` because when I try to run `esy mvim` on my project which depends on `engine.io-parser` for example, I get tons of error like `/Users/benjamin/Desktop/resocket.io/node_modules/.cache/esy-env: line 286: export: 'engine.io_parser__name=engine.io-parser': not a valid identifier`

**Comment by jordwalke** [comment]
We might also consider filtering out all of the totally not related to esy packages. (For example, if there's a package, such that every transitive dependency has no `esy:` config in their `package.json`, we might avoid setting up all the env vars. Right now, we spend time setting up env vars for tons of npm packages when you happen to depend on some.

**Comment by jordwalke** [comment]
I'm going to fix this right now. One other issue is that `@opam-alpha/foo` is converted to `opam_alpha_foo` in ejected makefile, which conflicts with a package named `opam-alpha-foo`. I will fix all of this, including the fact that packages with dots in their name cause issues.

- `/` would have to become `__slash__`.

We don't need to escape `@`, because it can never cause a conflict - only the slash can (if we're not careful).

This will be pretty ugly, but as long as they are merely variables in ejected (make / ninja), and never show up in `npm install` output or path names, we should be fine. Better to not fail / not conflict in the scripts with ugly internal variables, than to fail with beautiful variables.

**Comment by jordwalke** [comment]
On the other hand, on npm and opam alike, the `-` is far more common than the `_`, and `.` is even more rare (even forbidden in opam?) so it might be best to optimize for `-`, even though these don't surface to end users.

So in addition to escaping slash / dot like we discussed, we could do:

`-` (hyphen) becomes `_` (under).
`_` (under) becomes `__` (double under).
`__` becomes `___` (triple)

and so on. We just *add one* to the number of underscores.

The only thing this conflicts with is if our auto generated variable names need `__` to separate `packagename__var`, such as `react__version=10`. If that's the case, then you make sure `package-name` doesn't become `package__name` by adding *two* underscores.

`-` (hyphen) becomes `_` (under).
`_` (under) becomes `___` (triple under)
`__` becomes `____` (quadruple)

and so on.

**Comment by jordwalke** [comment]
Just like what's in `master`, this scheme is also nice because the normalized name never contains `-`, and the resulting name should be usable to use as a file name for cache directories, and *since* `-` is never used in the normalized name, it can be used as the version separator when written to a file like `normalized_name-versionxyz`.

**Comment by jordwalke** [comment]
This is now in our "master" `esy` branch now. I implemented cache purging as well across major esy version upgrades (you bump the version in the main `esy` shell script).

It purges build cache whenever you bump the build cache version number,
and it purges the yarn package cache whenever you uninstall/reinstall esy.
